### PR TITLE
Use NAN for wider engine support

### PR DESCRIPTION
**Pull request by pfmooney**
I ran test builds on Linux, OSX and SmartOS.
When running in a tight loop, there didn't appear to be any memory leaks.

### CODE REVIEW

**Comment by postwait** [comment]
This still works and compiles on node 0.8?

**Comment by pfmooney** [comment]
I'll check on that.

**Comment by pfmooney** [comment]
It installed/ran on all three platforms using 0.8.28.
(With the caveat that I upgraded to the latest npm prior to performing the node-libuuid install.)

**Comment by pfmooney** [comment]
Are there any other concerns you want addressed?

**Pull request merged**
